version: v1
# If advanced mode is active CI pipelines use Dockerfile and helm descriptor from repository
advancedMode:
  enabled: false
build:
  # recommendation: use the official composer repo if you want to change runtime version: https://hub.docker.com/_/composer
  image: docker.io/composer:2.3.10
  # definitions of environment variables that will be used in all stages of your pipeline
  environmentVariables: []
  #- key: variable1
  #  value: value1
  #- key: variable2
  #  value: value2
  #- key: variable3
  #  value: value3
  pipelines:
    release:
      pipeline: php-composer-app-release
    preview:
      pipeline: java-gradle-app-preview
    triggers: []
runtime:
  # Image is used as a base image for your runtime container
  image: docker.io/webdevops/php-nginx:8.0-alpine
  # Port on which the service will be exposed
  port: "80"
  endpoints:
    external:
      # Expose service to external endpoint
      enabled: true